---

# Hydra specifc options
hydra:
  help:
    template:
      'TODO: Add help message'
  run:
    dir:
      logs/${logging.name}/${now:%Y-%m-%d_%H-%M-%S}

# Set the mode: preprocess, train, test
mode: train

# Set the device to use (I'm not sure that I've properly implemented this everywhere)
device: gpu

# Set the path to the training data and the test/train/validation splits
data:
  datapath: data/pt
  train_split: 0.7
  test_split: 0.2
  val_split: 0.1
  # runs: [10000, 10001, 10002, 10003]
  runs: [10002]

# Set the input/output path when preprocessing the ROOT NTuples -> pytorch .pt files
preprocessing:
  runs: [10000, 10001, 10003]
  input_dirpath: /home/benwilson/data/pinpointG4_data/root
  output_dirpath: data/pt
  compute_edges: False # Requires GPU
  
# Configure the model parameters
model:
  architecture: FastGravNet
  n_classes: 4
  n_targets: 8
  embed_dim: 64
  grav_conv_dims: [64, 64, 64]
  propagate_dims: [16, 16, 16]
  knn: [16, 16, 16]
  space_dims: [4, 4, 4]
  downsample_frac: 0.5
  downsample_min_hits: 5000
  input_dim: 3 # 3 for x, y, z, pos
  dropout: 0.3
  do_classification: False
  do_regression: True
  

# Configure the training options
training:
  batch_size: 4
  max_epochs: 500
  learning_rate: 1e-4
  targets: [E_nu, E_vis, pT_miss, pT_lep, pT_jet, p_jet, p_lep, E_lep]
  # targets: [E_nu, E_vis, pT_miss, pT_jet, p_jet]
  # targets: [E_nu]
  classes: None
  num_workers: 4
  use_weights: False
  regression_loss_scale: 0.5 # In regr + class mode, factor to multiply the regression loss by
  accumulate_grad_batches: 512
  
  early_stopping:
    monitor: val_loss
    min_delta: 0.0
    patience: 40

# Configure the testing options
testing:
  run_dir: null  # Override this option to set the run directory
  batch_size: 32
  num_workers: 16
  checkpoint_dir: lightning_logs/version_0/checkpoints # Specify the checkpoint subdirectory. You shouldn't need to change this unless you've tweaked the logging dirs
  checkpoint_filepath: null # Specify the checkpoint file directly if given
  output_file: results.root # Name of the output file the resolution histograms get saved to

# Logging options
logging:
  name: energy_regression_${mode}
  monitor: val_loss
  mode: min
  save_top_k: 3
  verbose: False

# Plotting options
plotting:
  formats: ["png", "pdf"]
  dpi: 300


# Define some properties for the target variables; used when making the resolution plots
# The `bins` field is used to split the resolution by energy/eta/etc... range 
variables:

  E_nu: 
    name: "Neutrino Energy"
    latex: "E_{\\nu}"
    unit: "GeV"
    transformation: "log10"
    bins: [[0, 100], [100, 200], [200, 300], [300, 400], [400, 600], [600, 800], [800, 1000], [1000, .inf]]

  E_lep: 
    name: "Lepton Energy"
    latex: "E_{\\mathrm{lep}}"
    unit: "GeV"
    transformation: "log10"
    bins: [[0, 100], [100, 200], [200, 300], [300, 400], [400, 600], [600, 800], [800, 1000], [1000, .inf]]
  
  E_vis: 
    name: "Visible Energy"
    latex: "E_{\\mathrm{vis}}"
    unit: "GeV"
    transformation: "log10"
    bins: [[0, 100], [100, 200], [200, 300], [300, 400], [400, 600], [600, 800], [800, 1000], [1000, .inf]]
  
  E_miss: 
    name: "Missing Energy"
    latex: "E_{\\mathrm{miss}}"
    unit: "GeV"
    transformation: "log10"
    bins: [[0, 100], [100, 200], [200, 300], [300, 400], [400, 600], [600, 800], [800, 1000], [1000, .inf]]

  pT_miss: 
    name: "Missing Transverse Momentum"
    latex: "{p_{T}^{\\mathrm{miss}}}"
    unit: "GeV"
    transformation: "log10"
    bins: [[0, 5], [5, 10], [10, 20], [20, 30], [30, .inf]]

  pT_lep: 
    name: "Lepton Transverse Momentum"
    latex: "{p_{T}^{\\mathrm{lep}}}"
    unit: "GeV"
    transformation: "log10"
    bins: [[0, 5], [5, 10], [10, 20], [20, 30], [30, .inf]]

  pT_jet: 
    name: "Jet Transverse Momentum"
    latex: "{p_{T}^{\\mathrm{jet}}}"
    unit: "GeV"
    transformation: "log10"
    bins: [[0, 5], [5, 10], [10, 20], [20, 30], [30, .inf]]
  
  p_jet: 
    name: "Jet Momentum"
    latex: "{p^{\\mathrm{jet}}}"
    unit: "GeV"
    transformation: "log10"
    bins: [[0, 100], [100, 200], [200, 300], [300, 400], [400, 600], [600, 800], [800, 1000], [1000, .inf]]
  
  p_lep: 
    name: "Lepton Momentum"
    latex: "{p^{\\mathrm{lep}}}"
    unit: "GeV"
    transformation: "log10"
    bins: [[0, 100], [100, 200], [200, 300], [300, 400], [400, 600], [600, 800], [800, 1000], [1000, .inf]]
  


  # Eta_lep:
  #   name: "Lepton Pseudorapidity"
  #   latex: "\\eta_{\\mathrm{lep}}"
  #   unit: ""
  #   transformation: null
  #   bins: [[0, 3], [3, 4], [4, 5], [5, 6], [6,7], [7, 8], [8, .inf]]

  # E_had: 
  #   name: "Sum of Charged Hadron Energy"
  #   latex: "\\sum E_{\\mathrm{chg. had}}"
  #   unit: "GeV"
  #   transformation: "log10"
  #   bins: [[0, 100], [100, 200], [200, 300], [300, 400], [400, 600], [600, 800], [800, 1000], [1000, .inf]]


exp_name: "my experiment"  # Just a string that can be set to name an experiment. 